[package]
name = "ribbon_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
ribbon_lexer = { path = "../ribbon_lexer" }
ribbon_ast = { path = "../ribbon_ast" }
ribbon_error = { path = "../ribbon_error" }

[dev-dependencies]
insta = { version = "1.45.0", features = ["yaml"] }
