[package]
name = "ribbon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
ribbon_lexer = { path = "../ribbon_lexer" }
ribbon_parser = { path = "../ribbon_parser" }
